trigger:
  - master 
pool:
  vmImage: 'windows-latest'
variables:
  azureSubscription: 'Free Trial (4f8c978f-e970-4aa0-b8fe-541521351f0b)'
  appName: 'FunTestFunc'

stages:
- stage: Build
  displayName: 'Azure Function Build'
  jobs:
  - job:
    steps:
    - script: |
        dotnet restore
        dotnet build --configuration Release
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        arguments: '--configuration Release --output publish_output'
        projects: '*.csproj'
        publishWebProjects: false
        modifyOutputPath: false
        zipAfterPublish: false
    - task: ArchiveFiles@2
      displayName: "Archive files"
      inputs:
        rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
        includeRootFolder: false
        archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
        artifactName: 'drop'
- stage: Release
  displayName: 'Azure Function Release'
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - job:
    steps:
      - task: FuncToolsInstaller@0
        inputs:
           version: 'latest'
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(Pipeline.Workspace)'
          #cleanDestinationFolder: true
      - task: AzureFunctionApp@2 # Add this at the end of your file
        inputs:
          connectedServiceNameARM: '$(azureSubscription)'
          appType: 'functionAppLinux'
          appName: '$(appName)'
          deployToSlotOrASE: true
          resourceGroupName: 'terraformiac'
          slotName: 'production'
          package: '$(Pipeline.Workspace)/**/*.zip'
          runtimeStack: 'DOTNET-ISOLATED|8.0'
          deploymentMethod: 'zipDeploy'
          appSettings: |
              [
                {
                  "name": "WEBSITE_RUN_FROM_PACKAGE",
                  "value": "1",
                  "slotSetting": false
                }
              ]